version: '3'
services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog
    pid: host
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /:/host/root:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /etc/os-release:/etc/os-release
    environment:
      - DD_TAGS="env:emulation"
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_RUNTIME_SECURITY_CONFIG_ENABLED=true
      - DD_RUNTIME_SECURITY_CONFIG_NETWORK_ENABLED=true
      - DD_RUNTIME_SECURITY_CONFIG_REMOTE_CONFIGURATION_ENABLED=true
      - DD_REMOTE_CONFIGURATION_ENABLED=true
      - HOST_ROOT=/host/root
  atomicredteam:
    build: .
    container_name: atomicredteam